# Generated by Django 2.2.4 on 2020-10-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnum', models.PositiveIntegerField()),
                ('prop', models.CharField(max_length=5)),
                ('opp', models.CharField(max_length=5)),
                ('pscore', models.FloatField()),
                ('oscore', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnum', models.PositiveIntegerField()),
                ('team', models.CharField(max_length=5)),
                ('side', models.CharField(choices=[('Proposition', 'Proposition'), ('Opposition', 'Opposition')], default='Proposition', max_length=15)),
                ('motion', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnum', models.PositiveIntegerField()),
                ('prop', models.CharField(max_length=5)),
                ('opp', models.CharField(max_length=5)),
                ('p1j1', models.PositiveIntegerField(verbose_name='Confidence - J1')),
                ('p2j1', models.PositiveIntegerField(verbose_name='Organization Of Points - J1')),
                ('p3j1', models.PositiveIntegerField(verbose_name='Quality Of Arguments - J1')),
                ('p4j1', models.PositiveIntegerField(verbose_name='Engagement with Opposite Team - J1')),
                ('p5j1', models.PositiveIntegerField(verbose_name='Analysis - J1')),
                ('p6j1', models.PositiveIntegerField(verbose_name='Rapport established with Partner - J1')),
                ('p1j2', models.PositiveIntegerField(verbose_name='Confidence - J2')),
                ('p2j2', models.PositiveIntegerField(verbose_name='Organization Of Points - J2')),
                ('p3j2', models.PositiveIntegerField(verbose_name='Quality Of Arguments - J2')),
                ('p4j2', models.PositiveIntegerField(verbose_name='Engagement with Opposite Team - J2')),
                ('p5j2', models.PositiveIntegerField(verbose_name='Analysis - J2')),
                ('p6j2', models.PositiveIntegerField(verbose_name='Rapport established with Partner - J2')),
            ],
        ),
    ]
