# Generated by Django 2.2.4 on 2020-10-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201011_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='p1j1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='p1j2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='p2j1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='p2j2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='p3j1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='p3j2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='p4j1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='p4j2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='p5j1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='p5j2',
        ),
        migrations.RemoveField(
            model_name='score',
            name='p6j1',
        ),
        migrations.RemoveField(
            model_name='score',
            name='p6j2',
        ),
        migrations.AddField(
            model_name='score',
            name='s1p1j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Confidence - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s1p1j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Confidence - J2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s1p2j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Organization Of Points - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s1p2j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Organization Of Points - J2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s1p3j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Quality Of Arguments - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s1p3j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Quality Of Arguments - J2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s1p4j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Engagement with Opposite Team - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s1p4j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Engagement with Opposite Team - J2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s1p5j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Analysis - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s1p5j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Analysis - J2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s1p6j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Rapport established with Partner - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s1p6j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S1 - Rapport established with Partner - J2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p1j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Confidence - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p1j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Confidence - J2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p2j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Organization Of Points - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p2j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Organization Of Points - J2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p3j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Quality Of Arguments - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p3j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Quality Of Arguments - J2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p4j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Engagement with Opposite Team - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p4j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Engagement with Opposite Team - J2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p5j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Analysis - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p5j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Analysis - J2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p6j1',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Rapport established with Partner - J1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='s2p6j2',
            field=models.PositiveIntegerField(default=0, verbose_name='S2 - Rapport established with Partner - J2'),
            preserve_default=False,
        ),
    ]
