# Generated by Django 2.2.4 on 2020-11-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201012_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='opps1p1j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Diction and vocal delivery - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p1j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Diction and vocal delivery - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p2j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Organization Of Points - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p2j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Organization Of Points - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p3j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Quality Of Arguments - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p3j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Quality Of Arguments - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p4j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Engagement with Opposite Team - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p4j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Engagement with Opposite Team - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p5j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p5j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Analysis - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p6j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Coordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps1p6j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 1 - Coordination with partner - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p1j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Diction and vocal delivery - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p1j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Diction and vocal delivery - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p2j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Organization Of Points - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p2j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Organization Of Points - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p3j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Quality Of Arguments - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p3j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Quality Of Arguments - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p4j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Engagement with Opposite Team - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p4j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Engagement with Opposite Team - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p5j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p5j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Analysis - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p6j1',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Coordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='opps2p6j2',
            field=models.FloatField(default=0, verbose_name='Opposition Speaker 2 - Coordination with partner - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p1j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Diction and vocal delivery - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p1j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Confidence - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p2j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Organization Of Points - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p2j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Organization Of Points - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p3j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Quality Of Arguments - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p3j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Quality Of Arguments - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p4j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Engagement with Opposite Team - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p4j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Engagement with Opposite Team - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p5j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p5j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Analysis - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p6j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Coordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props1p6j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Coordination with partner - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p1j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Diction and vocal delivery - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p1j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Diction and vocal delivery - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p2j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Organization Of Points - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p2j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Organization Of Points - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p3j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Quality Of Arguments - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p3j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Quality Of Arguments - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p4j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Engagement with Opposite Team - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p4j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Engagement with Opposite Team - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p5j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Analysis - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p5j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Analysis - J2'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p6j1',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Coordination with partner - J1'),
        ),
        migrations.AlterField(
            model_name='score',
            name='props2p6j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 2 - Coordination with partner - J2'),
        ),
    ]
