# Generated by Django 2.2.4 on 2020-11-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201103_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='props1p1j2',
            field=models.FloatField(default=0, verbose_name='Proposition Speaker 1 - Diction and vocal delivery - J2'),
        ),
    ]
